security:
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_USER]

    password_hashers:
            App\Entity\User:
                algorithm: bcrypt
                cost: 12
    # Fournisseurs d'utilisateurs (vide pour l'instant)
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: mail

    # Le firewall gère les zones sécurisées de l'application
    firewalls:
        # Le firewall principal (toutes les pages accessibles sans connexion)
        main:
            stateless: false
            custom_authenticator: App\Security\UserAuthentificatorAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                # by default, the feature is enabled by checking a checkbox in the
                # login form, uncomment the following line to always enable it.
                #always_remember_me: true
            # Cela permet d'accepter toutes les requêtes sans authentification.
            # Aucune règle d'authentification spécifique appliquée ici.

    # Aucune restriction d'accès n'est définie
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN } # Protéger les routes commençant par /admin
        - { path: ^/profile, roles: ROLE_USER } # Protéger les routes commençant par /profile
        - { path: ^/boutique, roles: ROLE_USER }

