security:
    password_hashers:
            App\Entity\User:
                algorithm: bcrypt
                cost: 12
    # Fournisseurs d'utilisateurs (vide pour l'instant)
    providers:
        in_memory: { memory: null }

    # Le firewall gère les zones sécurisées de l'application
    firewalls:
        # Le firewall principal (toutes les pages accessibles sans connexion)
        main:
            stateless: true
            # Cela permet d'accepter toutes les requêtes sans authentification.
            # Aucune règle d'authentification spécifique appliquée ici.

    # Aucune restriction d'accès n'est définie
    access_control: []
